server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_db
        username: test_admin
        password: 1111

    jpa:
        show_sql: true
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true
